Teleporter (Fixed)
GDCASU/Color-Phase pull request #28
Opened 2018-11-28 07:00 UTC by danielwaker

Teleporter teleports player to another teleporter.

A cleaner pull request hopefully.

2019-02-01 20:29 UTC, content-deleted requested changes
Left some comments on the areas that you should look at.
BTW do you have a linter active? There are a lot of spacing changes to ColorSwap which is fine but interesting

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/ButtonToggle.cs
> +            if (other.gameObject.tag.StartsWith("Box"))
We shouldn't duplicate code like this, instead you should just check
            if (other.gameObject.tag.StartsWith("Player") || other.gameObject.tag.StartsWith("Box") ) ...

Also please use gameObject.CompareTag(String), I believe that tag.StartsWith is a relic of the multiplayer implementation

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/ButtonToggle.cs
> +                if (other.gameObject.tag.StartsWith("Box"))
See the long comment bellow

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/Box.cs
> +        if (Input.GetMouseButtonUp(0) && onHand == true)
Please use Zack's input manager he worked really hard on it

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/Box.cs
> +            gameObject.GetComponent<Rigidbody>().constraints = RigidbodyConstraints.None;
If you're making multiple calls to the component in Update you should definitely store a reference to that component instead of using GetComponent multiple times since it can start to impact performance, its honestly probably fine in a conditional like this but it does look cleaner

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/Box.cs
> +            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
Since the mouse is locked to the center of the screen you don't necessarily need to get the mouse position instead of using a constant

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/Box.cs
> +    private void OnCollisionEnter(Collision collision)
This is fine for now but as Connor suggested we should standardize collision between color objects using the layer system

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/ConveyorBelt.cs
> +        if (reverseDirection == false)
using a bang instead of equivalency to false is much cleaner ie 
if(!reverseDirection)

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/ConveyorBelt.cs
> +            obj.gameObject.GetComponent<Rigidbody>().velocity = obj.gameObject.GetComponent<Rigidbody>().velocity + beltVelocity * Time.deltaTime * transform.right;
Same as above with GetComponent

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/Teleport.cs
> +                    if (other.tag.StartsWith("Player"))
Already checked if tag is Player

2019-02-01 20:29 UTC, content-deleted commented on Assets/Scripts/Teleport.cs
> +    public double timer;
For the timer system if you use a static value you can make the system a lot less complicated. 
Ie onenter sets the value and then update decrements while its more then zero 0
if the value isnt zero then on enter can't teleport the player

2019-02-08 21:37 UTC, danielwaker commented
fixed everything hopefully

2019-02-15 21:58 UTC, merged