Scene controller
GDCASU/Color-Phase pull request #3
Opened 2018-07-12 04:06 UTC by taangle

Added scene controller with simple methods to change scenes. Instance in each level would need to have nextLevel and previousLevel set manually. Could easily be changed to support different types of level loading.

2018-07-24 03:41 UTC, Runi-c requested changes
I cleaned up the .gitignore and made a few comments on the SceneController about things I was unclear about or think should be changed. Feel free to look over, make changes, and explain anything I missed

2018-07-24 03:41 UTC, Keterr commented on Assets/Resources/Scripts/SceneController.cs
> +		// Should this funtion be made a coroutine so that the caller is forced to be aware of the asynchronicity?
If this function is made to return the result of LoadSceneAsync (an AsyncOperation) the caller can handle it any way it wants, which should be good enough for now

2018-07-24 03:41 UTC, Keterr commented on Assets/Resources/Scripts/SceneController.cs
> +	public static void GoToScene(string targetSceneName)
Shouldn't this function also update currentScene and previousScene (and probably nextScene as well)?

2018-07-24 03:41 UTC, Keterr commented on Assets/Resources/Scripts/SceneController.cs
> +	// currentScene populates in Start, previous and next need to be set manually
the SceneController should probably be the one responsible for deciding which scene to go to next at any given step, for starters an array that the SceneController (which would be on a DontDestroyOnLoad object) steps forward and back through

2018-08-08 06:23 UTC, taangle commented
@Keterr I changed everything to fit what we talked about. SceneController is now a DontDestroyOnLoad, although I purposely didn't make it an actual "singleton" (although it functionally will be one). There's now a SceneChanger script that can be attached to any object wanting to use the SceneController.

2018-08-21 03:05 UTC, Runi-c approved these changes

2018-08-21 03:05 UTC, merged